// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Icon(Props) {
  var name = Props.name;
  var sizeOpt = Props.size;
  var className = Props.className;
  var size = sizeOpt !== undefined ? sizeOpt : 20;
  var otherClasses = className !== undefined ? className : "";
  return React.createElement("svg", {
              className: "fill-current " + otherClasses,
              height: String(size) + "px",
              width: String(size) + "px"
            }, React.createElement("use", {
                  xlinkHref: "/icons/solid.svg#" + name
                }));
}

var make = Icon;

export {
  make ,
  
}
/* react Not a pure module */
