// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Icon$EditorUi from "./components/Icon.bs.js";
import * as CatSprite$EditorUi from "./components/CatSprite.bs.js";

require("tailwindcss/tailwind.css")
;

function Index$Sidebar(Props) {
  return React.createElement("div", {
              className: "w-60 flex-none h-full overflow-y-auto flex flex-col items-start p-2 border-r border-gray-200"
            }, React.createElement("div", {
                  className: "font-bold"
                }, "Events"), React.createElement("div", {
                  className: "flex flex-row flex-wrap bg-yellow-500 text-white px-2 py-1 my-2 text-sm cursor-pointer"
                }, "When ", React.createElement(Icon$EditorUi.make, {
                      name: "flag",
                      size: 15,
                      className: "text-green-600 mx-2"
                    }), "clicked"), React.createElement("div", {
                  className: "flex flex-row flex-wrap bg-yellow-500 text-white px-2 py-1 my-2 text-sm cursor-pointer"
                }, "When this sprite clicked"), React.createElement("div", {
                  className: "font-bold"
                }, "Motion"), React.createElement("div", {
                  className: "flex flex-row flex-wrap bg-blue-500 text-white px-2 py-1 my-2 text-sm cursor-pointer"
                }, "Move 10 steps"), React.createElement("div", {
                  className: "flex flex-row flex-wrap bg-blue-500 text-white px-2 py-1 my-2 text-sm cursor-pointer"
                }, "Turn ", React.createElement(Icon$EditorUi.make, {
                      name: "undo",
                      size: 15,
                      className: "text-white mx-2"
                    }), "15 degrees"), React.createElement("div", {
                  className: "flex flex-row flex-wrap bg-blue-500 text-white px-2 py-1 my-2 text-sm cursor-pointer"
                }, "Turn ", React.createElement(Icon$EditorUi.make, {
                      name: "redo",
                      size: 15,
                      className: "text-white mx-2"
                    }), "15 degrees"));
}

var Sidebar = {
  make: Index$Sidebar
};

function Index$MidArea(Props) {
  return React.createElement("div", {
              className: "flex-1 h-full overflow-auto"
            }, "mid area");
}

var MidArea = {
  make: Index$MidArea
};

function Index$PreviewArea(Props) {
  return React.createElement("div", {
              className: "flex-none h-full overflow-y-auto p-2"
            }, React.createElement(CatSprite$EditorUi.make, {}));
}

var PreviewArea = {
  make: Index$PreviewArea
};

function Index$App(Props) {
  return React.createElement("div", {
              className: "bg-blue-100 pt-6 font-sans"
            }, React.createElement("div", {
                  className: "h-screen overflow-hidden flex flex-row  "
                }, React.createElement("div", {
                      className: "flex-1 h-screen overflow-hidden flex flex-row bg-white border-t border-r border-gray-200 rounded-tr-xl mr-2"
                    }, React.createElement(Index$Sidebar, {}), React.createElement(Index$MidArea, {})), React.createElement("div", {
                      className: "w-1/3 h-screen overflow-hidden flex flex-row bg-white border-t border-l border-gray-200 rounded-tl-xl ml-2"
                    }, React.createElement(Index$PreviewArea, {}))));
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Index$App, {}), root);
}

export {
  Sidebar ,
  MidArea ,
  PreviewArea ,
  App ,
  
}
/*  Not a pure module */
